config/routes.rb
Rails.application.routes.draw do
  get '/signin', to: 'sessions#signin'
  get '/signout', to: 'sessions#signout'
  get '/users/signup', to: 'users#signup'

  resources :sessions, only: :create
  resources :users, except: :new
  resources :pictures, :comments, :tags, :picture_tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :picture_tags
  has_many :tags, through: :picture_tags
  has_one_attached :image
  accepts_nested_attributes_for :tags
  # validates :image_url, uniqueness: true
  # has_attached_file :image, styles: { large: "600x600>", medium: "300x300", thumb: "150x150#" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  def image=(uploaded_image)
       file_path = Rails.root.join('app', 'assets', 'images',uploaded_image.original_filename )

       File.open(file_path, 'wb') do |file|
           file.write(uploaded_image.read)
       end

       self.image_url = "http://localhost:3000/assets/#{uploaded_image.original_filename}"
   end

   def tag_names=(tag_names)
     tag_names.split(',').each do | tag_name |
       self.tags << Tag.create(name:tag_name)
     end
   end

end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
  belongs_to :picture
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :picture_tags
  has_many :pictures, through: :picture_tags
  validates :name, presence: true


  def self.most_popular
    x = Tag.all.map do |tag|
      tag.pictures.length
    end
    x.sort_by {|tag| tag}.reverse
    puts "#{x[0]}, #{x[1]}, #{x[2]}"
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :comments, through: :pictures
  validates :username, uniqueness: true
  validates :email, uniqueness: true
  has_secure_password


  def received_comments
    #should return all the comments made
    #on a picture that the user posted
    users_pictures = Picture.all.select {|picture| picture.user == self}
    return users_pictures.map {|user_picture| user_picture.comments}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :signed_in?
    before_action :signin_required

    def signin_required
      if !signed_in?
        redirect_to signin_path, :notice => "Please sign in to view pictures. It only takes a moment!"
      end
    end

    def signed_in?
      !!current_user
    end


    def current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      end


    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find.params[:id]
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find.params[:id]
  end

  def create
      @comment = Comment.new(comment_params)
      @comment.user_id = current_user.id
       if @comment.save
         redirect_to picture_path(@comment.picture)
       else
         redirect_to pictures_path
       end
    end

    def destroy
      @comment = Comment.find(params[:id])
      @picture = @comment.picture
      @comment.destroy
      redirect_to picture_path(@picture)
    end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :picture_id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all.order('created_at DESC')
  end

  def show
    @picture = Picture.find(params[:id])
    @comment = Comment.new
    @comment.user = current_user
    @comment.picture = @picture
    @comments = @picture.comments
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    # byebug
    # if params[:picture][:create_tag][:name]
    # then create the tag and redirect back to the picture new page
    # else if that doesn't exist
    # create the picture with the selected tag (or display error message if one is not selected)

    # if params[:picture][:create_tag][:name]
    #   byebug
    #   @tag = Tag.create(tag_params)
    #
    #   redirect_to new_picture_path
    # else
    @picture = Picture.new(picture_params)
    @picture.user = current_user
      if @picture.save
        redirect_to picture_path(@picture)
      else
        redirect_to new_picture_path
      end


  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to picture_path(@picture)
    else
      redirect_to edit_picture_path
    end
  end



  def destroy
    Picture.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end


  private

  def picture_params
    params.require(:picture).permit(:title, :user_id, :image_url, :image, {tag_ids:[]}, :tag_names)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :signin_required, :only => [:signin, :create]

   def signin
    @user = User.new
   end

   def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(current_user), :notice => "Welcome back, #{user.username}"
    else

      # flash[:error] = user.errors.full_messages[0]
      flash[:error] = "Invalid password, please enter again."
        # flash.now.alert = "Invalid password, please enter again."
        redirect_to signin_path
    end
  end

   def signout
    session[:user_id] = nil
    redirect_to users_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def new
   @tag = Tag.new
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  # def create
  #   @tag = Tag.new(tag_params)
  #   if @tag.save
  #     redirect_to show_picture_path(@tag)
  #   else
  #     redirect_to show_picture_path(@tag)
  #   end
  # end

  def create
  @tag = Tag.new(tag_params)
  @tag.user_id = current_user.id
  if @tag.save
    redirect_to picture_path(@tag.picture)
  else
    #show error message on page
    # render not redirect
    redirect_to picture_path(@tag.picture)
  end
end

  def update
  end

  def destroy
    Tag.find(params[:id]).destroy
    redirect_to picture_path
  end

   private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :signin_required, :only => [:signup, :create, :index]

  def index
    @users = User.all
  end

  def signup
   @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
        flash[:error] = "Password confirmation does not match."
      redirect_to users_signup_path
    end
  end

  def show
    @user = User.find(params[:id])
    @pictures = @user.pictures
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path
    end
  end


  def destroy
    User.find(params[:id]).destroy
    session[:user_id] = nil
    redirect_to users_path
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
<h1><%= comment.content %></h1>
<% end %>

app/views/comments/show.html.erb
<h1>New Comment</h1>
<p><%=@comment.content%></p>

app/views/layouts/_header.html.erb
<% if signed_in? %>
Do you have a pic, <%= current_user.username.capitalize %>? Share it with everyone!

<%=link_to "Sign Out", signout_path %>

<% else %>

<%= link_to "Please Sign In!!! ", signin_path %> Or <%= link_to "Sign Up", users_signup_path %>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/users">Home</a></li>
    <li class="breadcrumb-item"><a href="/pictures">Pictures</a></li>
    <li class="breadcrumb-item"><a href="/users/signup">Create Account</a></li>
  </ol>
</nav>


<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
     <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<h1> Edit Your Pic! </h1>
    <%= form_with model: @picture do |f| %>
    <%=f.label :title%>:
    <%= f.text_field :title %><br>
    <%=f.label :image_url %>:
    <%= f.file_field :image %><br>
    Or
    Paste url:
    <%= f.text_field :image_url %><br>
    <%= f.hidden_field :user_id%><br>

    <%= f.text_field :tag_names, placeholder: "New tag" %>

    <br> Or Choose <%= f.label :tags%>:

    <br><%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %></br>
    <%= f.submit value="Upload Picture" %> </br>



  <% end %>

app/views/pictures/index.html.erb
<% @pictures.each do |picture|%>
<h3><br> <%= link_to picture.title, picture %> </br></h3>
<br> <%= link_to (image_tag (picture.image_url), style:"height: auto; width: 400px;"), picture_path(picture) %> </br>
<% end %>

app/views/pictures/new.html.erb
<h1> Upload Your Pic! </h1>
    <%= form_with model: @picture do |f| %>
    <%=f.label :title%>:
    <%= f.text_field :title %><br>
    <%=f.label :image_url %>:
    <%= f.file_field :image %><br>
    Or
    Paste url:
    <%= f.text_field :image_url %><br>
    <%= f.hidden_field :user_id%><br>

    <%= f.text_field :tag_names, placeholder: "New tag" %>

    <br> Or Choose <%= f.label :tags%>:

    <br><%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %></br>
    <%= f.submit value="Upload Picture" %> </br>



  <% end %>

app/views/pictures/show.html.erb
<%if current_user.username != @picture.user.username%>
  <h5><%=button_to "Back to #{@picture.user.username}'s profile", @picture.user, :method => :get %></h5>
  <h5><%=button_to "Back to your Profile!", current_user, :method => :get %></h5>
<%else%>
  <h5><%=button_to "Back to your Profile!", current_user, :method => :get %></h5>
<%end%>


<h1><%= @picture.title %></h1>
<%= (image_tag (@picture.image_url), style:"height: auto; width: 500px;") %>
<%if @picture.user.id == current_user.id%>
  <h5><%= button_to "Edit Picture", edit_picture_path(@picture), :method => :get %></h5>
  <h5><%= button_to "Delete Picture", picture_path(@picture), :method => :delete %></h5>
<%end%>

<h3>Tags:</h3><% @picture.tags.each do |tag|%>
<h3> <%=link_to tag.name, tag_path(tag)%> </h3>
<%end%>


<h3> Comment on this picture: <h3>
<%= form_with model: @comment do |f| %>
  <%= f.text_area :content %> <br>
  <%= f.hidden_field :picture_id %> <br>
  <%= f.hidden_field :user_id %> <br>
<h5>  <%= f.submit %> </h5>
<% end %><br>

<% @comments.each do |comment| %>
<h3><%= link_to comment.user.username, user_path(comment.user) %> : <%= comment.content %> <br> </h3>
<%if comment.user.id == current_user.id || @picture.user.id == current_user.id%>

  <h5> <%= button_to "Delete Comment", comment, :method => 'delete' %><br> </h5>


<%end%>

<% end %>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
<h1> <%= link_to tag.name, tag %> </h1>
<% end %>

app/views/tags/show.html.erb
<h1>Here are <%=@tag.name%> pics!</h1>
  <% @tag.pictures.each do |picture| %>
  <ul>
    <li><h2><%= picture.title %></li></h2>
    <h3><%= image_tag picture.image_url, style:"height: auto; width: 500px;"%></h3>
      </ul>
  <%end%>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1> Edit User Info <h1>
 <%= form_with model:@user do |f| %>
Username: <%= f.text_field :username %> <br>
Email: <%= f.text_field :email %> <br>
Password: <%= f.password_field :password %> <br>
Please confirm your new password: <%= f.password_field :password_confirmation%> <br>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<!-- <h3><button type="button" class="btn btn-outline-primary"><%= link_to ("Create Account!"), users_signup_path %></button></h3> -->

<h4>Usernames</h4>
<% @users.each do |user| %>
<h4><%= link_to user.username.downcase, user_path(user) %> </h4>
<% end %>

app/views/users/new.html.erb
<h1> Create Your Account! </h1>


<%= flash[:error]   %>
<%= form_with model: @user do |f| %>
Username: <%= f.text_field :username %> <br>
Email: <%= f.text_field :email %> <br>
Password: <%= f.password_field :password %> <br>
Confirm your password: <%= f.password_field :password_confirmation%> <br>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%if @user.id == current_user.id%>
  <h2><%=link_to "Upload Dog Pics", new_picture_path %></h2>
<% end %>

  <%if @user.pictures.empty?%>
    <h4>Currently No Pictures</h4>
  <%else%>
    <%if @user.id == current_user.id%>
      <h4>Here are your pics!</h4>
    <%else%>
      <h4>Here are <%= @user.username %>'s pics: </h4>
    <%end%>
      <%@pictures.order('created_at DESC').each do |picture| %>
      <h3><%= picture.title %><h3>
        <%= link_to (image_tag (picture.image_url), style:"height: auto; width: 400px;"), picture_path(picture) %><br>
    <% end %>
  <%end%>

 <%if @user.id == current_user.id%>
   <%= link_to "Delete Account", user_path(@user), :method => 'delete' %><br>
 <%end%>

app/views/users/signup.html.erb
<h1> Create Your Account! </h1>

<%= flash[:error] %>

<%= form_for @user do |f| %>
Username: <%= f.text_field :username %> <br>
Email: <%= f.text_field :email %> <br>
Password: <%= f.password_field :password %> <br>
Confirm your password: <%= f.password_field :password_confirmation%> <br>
<%= f.submit %>

<% end %>

<!-- <div class="ui animated button" tabindex="0">
  <div class="visible content">Next</div>
  <div class="hidden content">
    <i class="right arrow icon"></i>
  </div>
</div> -->